### ISSUE TITLE
Is this official ?

### ISSUE THREAD

**Issue by zekunyan** [chmeeedalf/lf-foundation#1]
I want to know if this repository is official implementation of Foundation ?

**Comment by chmeeedalf** [comment]
This is not an official Apple repository, no.  This was my effort (still might be, if I decide to go back to it), to create a Foundation API implementation dropping all interfaces that Apple deprecated which I consider obsolete (any that I still consider appropriate I kept)

**Comment by zekunyan** [comment]
Thanks. Excellent job !
